# Generated by Django 5.0.2 on 2024-03-04 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type_service",
                    models.CharField(
                        choices=[
                            ("TRANSFERT", "TRANSFERT"),
                            ("MISE-A-DISPOSITION", "MISE-A-DISPOSITION"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "car",
                    models.CharField(
                        choices=[
                            ("4X4", "4X4"),
                            ("CITADINE", "CITADINE"),
                            ("MINIBUS", "MINIBUS"),
                        ],
                        max_length=100,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Devis", "Devis"),
                            ("Facture", "Facture"),
                            ("Avoir", "Avoir"),
                        ],
                        default="Devis",
                        max_length=100,
                    ),
                ),
                ("start_city", models.CharField(max_length=100)),
                ("end_city", models.CharField(max_length=100)),
                ("date_start", models.DateField()),
                ("time_start", models.TimeField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("duration", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="invoices", to="services.service"
                    ),
                ),
            ],
        ),
    ]
