# Generated by Django 5.0.2 on 2024-03-04 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="document_type",
            new_name="name",
        ),
    ]
