# Generated by Django 5.0.2 on 2024-03-03 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("services", "0002_remove_service_end_date_remove_service_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="end_city",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="service",
            name="start_city",
        ),
        migrations.AddField(
            model_name="service",
            name="car",
            field=models.CharField(
                choices=[
                    ("4X4", "4X4"),
                    ("CITADINE", "CITADINE"),
                    ("MINIBUS", "MINIBUS"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_city", models.CharField(max_length=100)),
                ("end_city", models.CharField(max_length=100)),
                ("date_start", models.DateField()),
                ("time_start", models.TimeField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("duration", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="invoices", to="services.service"
                    ),
                ),
            ],
        ),
    ]
