# Generated by Django 5.0.2 on 2024-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_rename_document_type_invoice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="duration",
            field=models.IntegerField(default=1),
        ),
    ]
