# Generated by Django 5.0.2 on 2024-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_service_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="advance_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
