# Generated by Django 5.0.2 on 2024-03-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0003_rename_end_city_service_name_remove_service_duration_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Devis", "Devis"),
                    ("Facture", "Facture"),
                    ("Avoir", "Avoir"),
                ],
                default="Devis",
                max_length=100,
            ),
        ),
    ]
