# Generated by Django 5.0.2 on 2024-05-08 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_invoice_advance_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="duration",
        ),
    ]
