# Generated by Django 5.0.2 on 2024-05-07 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_address_1_client_address_2_client_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="address_1",
        ),
        migrations.RemoveField(
            model_name="client",
            name="address_2",
        ),
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
        migrations.RemoveField(
            model_name="client",
            name="company",
        ),
        migrations.RemoveField(
            model_name="client",
            name="country",
        ),
        migrations.RemoveField(
            model_name="client",
            name="zip_code",
        ),
    ]
